import { ComponentSchema, FieldMetadata } from '../FieldMetadata';
import { EFFECT_TARGET_OPTIONS, EFFECT_TYPE_OPTIONS, STORE_EFFECT_SUBJECT_OPTIONS } from '../../../schema';

const EFFECT_TYPE_ICONS: Record<string, string> = {
  teleport: 'adjustments',
  kill: 'close',
  getPickedUp: 'user',
  addToInventory: 'add',
  removeFromInventory: 'close',
  incrementStock: 'adjustments',
  setMetric: 'edit',
  incrementMetric: 'plusMinus',
  damage: 'health',
  heal: 'health',
  spawnEntityFrom: 'add',
  spawnAtHit: 'add',
  emitParticles: 'animation',
  emitEvent: 'info',
  mount: 'tool',
  discover: 'experiment',
  popup: 'info',
};

const ParticleShapeField: FieldMetadata = {
  name: 'shape',
  type: 'object',
  required: false,
  defaultValue: { type: 'point' },
  fields: {
    type: {
      name: 'type',
      type: 'enum',
      required: true,
      enumValues: ['point', 'box', 'sphere'],
      enumOptions: [
        { value: 'point', label: 'point', icon: 'point' },
        { value: 'box', label: 'box', icon: 'box' },
        { value: 'sphere', label: 'sphere', icon: 'sphere' },
      ],
      defaultValue: 'point',
      displayMode: 'compact',
      compactLabelMode: 'none',
      compactRow: 'shape_type',
    },
    params: {
      name: 'params',
      type: 'union',
      required: false,
      discriminator: 'type',
      unionTypes: {
        point: [],
        box: [
          {
            name: 'size',
            type: 'vector3',
            required: false,
            defaultValue: { x: 1, y: 1, z: 1 },
            displayMode: 'compact',
            icon: 'scale',
            condensedLabel: 'XYZ',
          },
        ],
        sphere: [
          {
            name: 'radius',
            type: 'number',
            required: false,
            defaultValue: 1,
            min: 0,
            step: 0.1,
            displayMode: 'compact',
            icon: 'radius',
            iconOnly: true,
          },
        ],
      },
    },
  },
};

const ParticleEmitterField: FieldMetadata = {
  name: 'emitter',
  type: 'object',
  required: true,
  fields: {
    rate: {
      name: 'rate',
      type: 'number',
      required: false,
      min: 0,
      step: 1,
      defaultValue: 0,
      compactRow: 'emit_rate',
      displayMode: 'compact',
      icon: 'timeline',
      iconOnly: true,
    },
    burst: {
      name: 'burst',
      type: 'number',
      required: false,
      min: 0,
      step: 1,
      defaultValue: 0,
      compactRow: 'emit_rate',
      displayMode: 'compact',
      icon: 'add',
      iconOnly: true,
    },
    maxParticles: {
      name: 'maxParticles',
      type: 'number',
      required: false,
      min: 1,
      step: 1,
      defaultValue: 100,
      compactRow: 'emit_rate',
      displayMode: 'compact',
      icon: 'users',
      iconOnly: true,
    },
    lifetime: {
      name: 'lifetime',
      type: 'number',
      required: false,
      min: 0,
      step: 0.1,
      defaultValue: 1,
      compactRow: 'emit_time',
      displayMode: 'compact',
      icon: 'animation',
      iconOnly: true,
    },
    duration: {
      name: 'duration',
      type: 'number',
      required: false,
      min: 0,
      step: 0.1,
      defaultValue: 0,
      compactRow: 'emit_time',
      displayMode: 'compact',
      icon: 'play',
      iconOnly: true,
    },
    speed: {
      name: 'speed',
      type: 'number',
      required: false,
      min: 0,
      step: 0.1,
      defaultValue: 1,
      compactRow: 'emit_time',
      displayMode: 'compact',
      icon: 'motion',
      iconOnly: true,
    },
    spread: {
      name: 'spread',
      type: 'number',
      required: false,
      min: 0,
      step: 0.1,
      defaultValue: 0.5,
      compactRow: 'emit_style',
      displayMode: 'compact',
      icon: 'adjustments',
      iconOnly: true,
    },
    size: {
      name: 'size',
      type: 'number',
      required: false,
      min: 0,
      step: 0.05,
      defaultValue: 0.2,
      compactRow: 'emit_style',
      displayMode: 'compact',
      icon: 'scale',
      iconOnly: true,
    },
    opacity: {
      name: 'opacity',
      type: 'number',
      required: false,
      min: 0,
      max: 1,
      step: 0.05,
      defaultValue: 1,
      compactRow: 'emit_style',
      displayMode: 'compact',
      icon: 'opacity',
      iconOnly: true,
    },
    gravity: {
      name: 'gravity',
      type: 'number',
      required: false,
      step: 0.1,
      defaultValue: 0,
      compactRow: 'emit_space',
      displayMode: 'compact',
      icon: 'arrowDown',
      iconOnly: true,
    },
    color: {
      name: 'color',
      type: 'color',
      required: false,
      compactRow: 'emit_space',
    },
    direction: {
      name: 'direction',
      type: 'vector3',
      required: false,
      defaultValue: { x: 0, y: 1, z: 0 },
      displayMode: 'compact',
      condensedLabel: 'XYZ',
      icon: 'arrowUp',
    },
    shape: ParticleShapeField,
    localSpace: {
      name: 'localSpace',
      type: 'boolean',
      required: false,
      defaultValue: false,
      displayMode: 'compact',
      icon: 'world',
      iconOnly: true,
    },
  },
};

const StoreSubjectField: FieldMetadata = {
  name: 'subject',
  type: 'enum',
  required: false,
  enumValues: [...STORE_EFFECT_SUBJECT_OPTIONS],
  defaultValue: 'target',
  displayMode: 'compact',
  icon: 'user',
  iconOnly: true,
};

export const EffectField: any = {
  name: 'effect',
  type: 'moduleReference',
  required: true,
  moduleName: 'effect',
  fields: {
    type: {
      name: 'type',
      type: 'enum',
      enumValues: [...EFFECT_TYPE_OPTIONS],
      enumOptions: [...EFFECT_TYPE_OPTIONS].map((value) => ({
        value,
        label: value,
        icon: EFFECT_TYPE_ICONS[value] ?? 'effect',
      })),
      required: true,
      defaultValue: 'damage',
      label: 'Effect Type',
      displayMode: 'compact',
      compactLabelMode: 'none',
      compactRow: 'effect_type',
    },
    target: {
      name: 'target',
      type: 'enum',
      enumValues: [...EFFECT_TARGET_OPTIONS],
      required: false,
      defaultValue: 'other',
      displayMode: 'compact',
      icon: 'user',
      iconOnly: true,
      compactRow: 'effect_scope',
    },
    range: {
      name: 'range',
      type: 'number',
      required: false,
      min: 0,
      step: 0.1,
      displayMode: 'compact',
      icon: 'radius',
      iconOnly: true,
      compactRow: 'effect_scope',
    },
    params: {
      name: 'params',
      type: 'union',
      discriminator: 'type',
      required: false,
      unionTypes: {
        teleport: [
          {
            name: 'position',
            type: 'vector3',
            required: true,
            label: 'Position',
            displayMode: 'compact',
            condensedLabel: 'XYZ',
            icon: 'adjustments',
          }
        ],
        kill: [],
        getPickedUp: [],
        addToInventory: [
          {
            name: 'item',
            type: 'moduleReference',
            required: true,
            moduleName: 'archetype',
            description: 'Archetype name or bundle to add',
          },
          {
            name: 'count',
            type: 'number',
            required: false,
            defaultValue: 1,
            min: 1,
            step: 1,
            displayMode: 'compact',
            icon: 'plusMinus',
            iconOnly: true,
          },
          { ...StoreSubjectField },
        ],
        removeFromInventory: [
          {
            name: 'archetype',
            type: 'string',
            required: false,
            defaultValue: '',
            displayMode: 'compact',
            icon: 'archive',
            iconOnly: true,
          },
          {
            name: 'name',
            type: 'string',
            required: false,
            defaultValue: '',
            displayMode: 'compact',
            icon: 'info',
            iconOnly: true,
          },
          {
            name: 'count',
            type: 'number',
            required: false,
            defaultValue: 1,
            min: 1,
            step: 1,
            displayMode: 'compact',
            icon: 'plusMinus',
            iconOnly: true,
          },
          { ...StoreSubjectField },
        ],
        incrementStock: [
          {
            name: 'stock',
            type: 'string',
            required: true,
            defaultValue: 'health',
            displayMode: 'compact',
            icon: 'settings',
            iconOnly: true,
          },
          {
            name: 'delta',
            type: 'number',
            required: false,
            defaultValue: 1,
            step: 1,
            displayMode: 'compact',
            icon: 'plusMinus',
            iconOnly: true,
          },
          { ...StoreSubjectField },
        ],
        setMetric: [
          {
            name: 'metric',
            type: 'string',
            required: true,
            defaultValue: 'score',
            displayMode: 'compact',
            icon: 'chartBar',
            iconOnly: true,
          },
          {
            name: 'value',
            type: 'number',
            required: true,
            defaultValue: 0,
            step: 1,
            displayMode: 'compact',
            icon: 'edit',
            iconOnly: true,
          },
          {
            name: 'subtype',
            type: 'string',
            required: false,
            defaultValue: '',
            displayMode: 'compact',
            icon: 'braces',
            iconOnly: true,
          },
          {
            name: 'subpath',
            type: 'string',
            required: false,
            defaultValue: '',
            displayMode: 'compact',
            icon: 'braces',
            iconOnly: true,
          },
          { ...StoreSubjectField },
        ],
        incrementMetric: [
          {
            name: 'metric',
            type: 'string',
            required: true,
            defaultValue: 'score',
            displayMode: 'compact',
            icon: 'chartBar',
            iconOnly: true,
          },
          {
            name: 'delta',
            type: 'number',
            required: false,
            defaultValue: 1,
            step: 1,
            displayMode: 'compact',
            icon: 'plusMinus',
            iconOnly: true,
          },
          {
            name: 'subtype',
            type: 'string',
            required: false,
            defaultValue: '',
            displayMode: 'compact',
            icon: 'braces',
            iconOnly: true,
          },
          {
            name: 'subpath',
            type: 'string',
            required: false,
            defaultValue: '',
            displayMode: 'compact',
            icon: 'braces',
            iconOnly: true,
          },
          { ...StoreSubjectField },
        ],
        damage: [
          {
            name: 'amount',
            type: 'number',
            required: false,
            defaultValue: 10,
            step: 1,
            compactRow: 'damage_row',
            displayMode: 'compact',
            icon: 'health',
            iconOnly: true,
          },
          {
            name: 'knockback',
            type: 'number',
            required: false,
            defaultValue: 0,
            step: 0.1,
            compactRow: 'damage_row',
            displayMode: 'compact',
            icon: 'arrowRight',
            iconOnly: true,
          }
        ],
        heal: [
          {
            name: 'amount',
            type: 'number',
            required: false,
            defaultValue: 10,
            step: 1,
            displayMode: 'compact',
            icon: 'health',
            iconOnly: true,
          }
        ],
        spawnEntityFrom: [
          {
            name: 'entity',
            type: 'moduleReference',
            required: true,
            moduleName: 'archetype',
            description: 'Archetype name or bundle to spawn'
          },
          {
            name: 'velocity',
            type: 'number',
            required: false,
            defaultValue: 0,
            step: 0.1,
            displayMode: 'compact',
            icon: 'motion',
            iconOnly: true,
          }
        ],
        spawnAtHit: [
          {
            name: 'entity',
            type: 'moduleReference',
            required: true,
            moduleName: 'archetype',
            description: 'Archetype name or bundle to spawn at the raycast hit'
          },
          {
            name: 'velocity',
            type: 'number',
            required: false,
            defaultValue: 0,
            step: 0.1,
            displayMode: 'compact',
            icon: 'motion',
            iconOnly: true,
          }
        ],
        emitParticles: [
          { ...ParticleEmitterField, name: 'emitter', description: 'Particle emitter definition' },
          {
            name: 'position',
            type: 'vector3',
            required: false,
            label: 'Position Override',
            displayMode: 'compact',
            condensedLabel: 'XYZ',
            icon: 'adjustments',
          },
          {
            name: 'duration',
            type: 'number',
            required: false,
            defaultValue: 0,
            step: 0.1,
            displayMode: 'compact',
            icon: 'play',
            iconOnly: true,
          }
        ],
        emitEvent: [
          {
            name: 'name',
            type: 'string',
            required: true,
            defaultValue: 'my_event',
            displayMode: 'compact',
            icon: 'info',
            iconOnly: true,
          },
          { name: 'payload', type: 'object', required: false, fields: {}, description: 'Optional event payload' }
        ],
        mount: [
          {
            name: 'offset',
            type: 'vector3',
            required: false,
            label: 'Offset',
            displayMode: 'compact',
            condensedLabel: 'XYZ',
            icon: 'adjustments',
          }
        ],
        discover: [],
        popup: [
          {
            name: 'text',
            type: 'string',
            required: true,
            defaultValue: '',
            displayMode: 'compact',
            icon: 'info',
            iconOnly: true,
          }
        ]
      }
    },
    onSuccess: {
      name: 'onSuccess',
      type: 'array',
      required: false,
      itemType: undefined as any,
      label: 'On Success'
    },
    onFailure: {
      name: 'onFailure',
      type: 'array',
      required: false,
      itemType: undefined as any,
      label: 'On Failure'
    }
  }
};

EffectField.fields.onSuccess.itemType = EffectField;
EffectField.fields.onFailure.itemType = EffectField;

export const EffectArrayField: FieldMetadata = {
  name: 'effects',
  type: 'array',
  required: true,
  itemType: EffectField,
  label: 'Effects'
};
