import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const checkOnly = process.argv.includes('--check');

const generatedHeader = '<!-- Generated by scripts/generate-docs.mjs. Do not edit by hand. -->';

const paths = {
  commandSource: path.join(repoRoot, 'engine/src/automation/definitions.ts'),
  resourceSource: path.join(repoRoot, 'engine/src/automation/resourceCatalog.ts'),
  referenceDir: path.join(repoRoot, 'docs/reference'),
  agentDir: path.join(repoRoot, 'docs/agents'),
};

const staticResourceUris = {
  'session-info': 'engine://session/info',
  'world-state-summary': 'engine://world/summary',
  'component-catalog': 'engine://components/catalog',
  'module-type-catalog': 'engine://modules/types',
  'module-instance-catalog': 'engine://modules/instances',
  'entity-list': 'engine://entities',
  'selected-entities-full': 'engine://selection/entities',
  'selected-body-parts-full': 'engine://selection/body-parts',
  metadata: 'engine://world/metadata',
  achievements: 'engine://world/achievements',
  'full-world-state': 'engine://world/full-state',
  'render-screenshot': 'engine://render/screenshot',
  'viewport-camera': 'engine://viewport/camera',
};

const templateResourceUris = {
  'entity-bundle': 'engine://entities/{stableId}',
  'entity-render-screenshot': 'engine://render/entities/{stableId}/screenshot',
};

function extractArrayLiteral(source, constName) {
  const marker = `export const ${constName}`;
  const markerIndex = source.indexOf(marker);
  if (markerIndex === -1) {
    throw new Error(`Could not find ${constName}`);
  }

  const equalsIndex = source.indexOf('=', markerIndex);
  if (equalsIndex === -1) {
    throw new Error(`Could not find assignment for ${constName}`);
  }

  const firstBracket = source.indexOf('[', equalsIndex);
  if (firstBracket === -1) {
    throw new Error(`Could not find array literal for ${constName}`);
  }

  let depth = 0;
  let quote = null;
  let escaped = false;

  for (let index = firstBracket; index < source.length; index += 1) {
    const char = source[index];

    if (quote) {
      if (escaped) {
        escaped = false;
      } else if (char === '\\') {
        escaped = true;
      } else if (char === quote) {
        quote = null;
      }
      continue;
    }

    if (char === '"' || char === "'" || char === '`') {
      quote = char;
      continue;
    }

    if (char === '[') {
      depth += 1;
    } else if (char === ']') {
      depth -= 1;
      if (depth === 0) {
        return source.slice(firstBracket, index + 1);
      }
    }
  }

  throw new Error(`Could not parse array literal for ${constName}`);
}

function evaluateArrayLiteral(arrayLiteral, constName) {
  try {
    return Function(`"use strict"; return (${arrayLiteral});`)();
  } catch (error) {
    throw new Error(`Failed to evaluate ${constName}: ${error.message}`);
  }
}

async function readCatalogs() {
  const [commandSource, resourceSource] = await Promise.all([
    fs.readFile(paths.commandSource, 'utf8'),
    fs.readFile(paths.resourceSource, 'utf8'),
  ]);

  const commands = evaluateArrayLiteral(
    extractArrayLiteral(commandSource, 'ENGINE_AUTOMATION_COMMAND_DEFINITIONS'),
    'ENGINE_AUTOMATION_COMMAND_DEFINITIONS',
  );
  const resources = evaluateArrayLiteral(
    extractArrayLiteral(resourceSource, 'ENGINE_AUTOMATION_RESOURCE_DEFINITIONS'),
    'ENGINE_AUTOMATION_RESOURCE_DEFINITIONS',
  );

  return { commands, resources };
}

function requiredText(value) {
  return value ? 'yes' : 'no';
}

function escapePipes(value) {
  return String(value).replaceAll('|', '\\|').replaceAll('\n', ' ');
}

function formatParameters(parameters = []) {
  if (!parameters.length) {
    return 'No parameters.';
  }

  const rows = parameters.map((parameter) => (
    `| \`${parameter.name}\` | \`${parameter.type ?? 'value'}\` | ${requiredText(parameter.required)} | ${escapePipes(parameter.description)} |`
  ));

  return [
    '| Name | Type | Required | Description |',
    '| --- | --- | --- | --- |',
    ...rows,
  ].join('\n');
}

function formatResourceParameters(parameters = []) {
  if (!parameters.length) {
    return 'No parameters.';
  }

  const rows = parameters.map((parameter) => (
    `| \`${parameter.name}\` | ${escapePipes(parameter.description)} |`
  ));

  return [
    '| Name | Description |',
    '| --- | --- |',
    ...rows,
  ].join('\n');
}

function commandJson(commands) {
  return {
    generatedFrom: 'engine/src/automation/definitions.ts',
    generatedBy: 'scripts/generate-docs.mjs',
    commands,
  };
}

function resourceUri(resource) {
  if (resource.kind === 'static') {
    return staticResourceUris[resource.name] ?? null;
  }

  return templateResourceUris[resource.name] ?? null;
}

function resourceJson(resources) {
  return {
    generatedFrom: 'engine/src/automation/resourceCatalog.ts',
    generatedBy: 'scripts/generate-docs.mjs',
    resources: resources.map((resource) => ({
      ...resource,
      mcpUri: resourceUri(resource),
    })),
  };
}

function renderCommandMarkdown(commands) {
  const toc = commands.map((command) => `- [\`${command.name}\`](#${command.name})`).join('\n');
  const sections = commands.map((command) => {
    const badges = [
      command.changesState ? '`changesState`' : '`readOnlyOrSessionOnly`',
      command.persistsWorld ? '`persistsWorld`' : null,
    ].filter(Boolean).join(' ');

    return [
      `## ${command.name}`,
      '',
      command.description,
      '',
      badges,
      '',
      formatParameters(command.parameters),
    ].join('\n');
  });

  return [
    generatedHeader,
    '# Automation Commands',
    '',
    'Generated from `engine/src/automation/definitions.ts`.',
    '',
    'Automation commands are exposed through `@gizmo3d/engine/automation`, `gizmo call`, `gizmo batch`, and MCP tools.',
    '',
    toc,
    '',
    sections.join('\n\n'),
    '',
  ].join('\n');
}

function renderResourceMarkdown(resources) {
  const toc = resources.map((resource) => `- [\`${resource.name}\`](#${resource.name})`).join('\n');
  const sections = resources.map((resource) => {
    const uri = resourceUri(resource);
    return [
      `## ${resource.name}`,
      '',
      resource.description,
      '',
      `Kind: \`${resource.kind}\``,
      '',
      `MIME type: \`${resource.mimeType}\``,
      '',
      uri ? `MCP URI: \`${uri}\`` : 'MCP URI: not mapped',
      '',
      resource.aliases?.length ? `Aliases: ${resource.aliases.map((alias) => `\`${alias}\``).join(', ')}` : 'Aliases: none',
      '',
      formatResourceParameters(resource.parameters),
    ].join('\n');
  });

  return [
    generatedHeader,
    '# Automation Resources',
    '',
    'Generated from `engine/src/automation/resourceCatalog.ts`.',
    '',
    'Automation resources are exposed through `@gizmo3d/engine/automation`, `gizmo resource`, and MCP resources/templates.',
    '',
    toc,
    '',
    sections.join('\n\n'),
    '',
  ].join('\n');
}

function renderPromptContext(commands, resources) {
  const commandLines = commands.map((command) => {
    const params = command.parameters?.map((parameter) => `${parameter.name}${parameter.required ? '' : '?'}`).join(', ') || 'none';
    const flags = [
      command.changesState ? 'changes state' : 'read/session',
      command.persistsWorld ? 'persists world' : null,
    ].filter(Boolean).join('; ');
    return `- ${command.name}(${params}): ${command.description}${flags ? ` [${flags}]` : ''}`;
  });

  const resourceLines = resources.map((resource) => {
    const params = resource.parameters?.map((parameter) => parameter.name).join(', ') || 'none';
    const uri = resourceUri(resource);
    return `- ${resource.name}${uri ? ` (${uri})` : ''}: ${resource.description} params: ${params}`;
  });

  return [
    generatedHeader,
    '# Gizmo Agent Prompt Context',
    '',
    'Generated from engine automation command and resource catalogs.',
    '',
    'Use resources to inspect world state before making changes. Prefer stable IDs for repeatable entity targeting. Mutating commands may persist the backing world file depending on session mode. JavaScript/MJS worlds can execute code and should only be opened from trusted workspaces.',
    '',
    '## Commands',
    '',
    ...commandLines,
    '',
    '## Resources',
    '',
    ...resourceLines,
    '',
  ].join('\n');
}

async function writeOrCheck(filePath, content) {
  if (checkOnly) {
    let current = null;
    try {
      current = await fs.readFile(filePath, 'utf8');
    } catch {
      throw new Error(`${path.relative(repoRoot, filePath)} is missing. Run npm run docs:generate.`);
    }
    if (current !== content) {
      throw new Error(`${path.relative(repoRoot, filePath)} is stale. Run npm run docs:generate.`);
    }
    return;
  }

  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content);
}

async function main() {
  const { commands, resources } = await readCatalogs();

  const outputs = [
    [
      path.join(paths.referenceDir, 'automation-commands.generated.md'),
      renderCommandMarkdown(commands),
    ],
    [
      path.join(paths.referenceDir, 'automation-commands.generated.json'),
      `${JSON.stringify(commandJson(commands), null, 2)}\n`,
    ],
    [
      path.join(paths.referenceDir, 'automation-resources.generated.md'),
      renderResourceMarkdown(resources),
    ],
    [
      path.join(paths.referenceDir, 'automation-resources.generated.json'),
      `${JSON.stringify(resourceJson(resources), null, 2)}\n`,
    ],
    [
      path.join(paths.agentDir, 'prompt-context.generated.md'),
      renderPromptContext(commands, resources),
    ],
  ];

  for (const [filePath, content] of outputs) {
    await writeOrCheck(filePath, content);
  }

  const mode = checkOnly ? 'validated' : 'generated';
  console.log(`Docs ${mode}: ${outputs.map(([filePath]) => path.relative(repoRoot, filePath)).join(', ')}`);
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
