import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const checkOnly = process.argv.includes('--check');

const skillPath = path.join(repoRoot, '.agents/skills/gizmo/SKILL.md');
const commandSourcePath = path.join(repoRoot, 'engine/src/automation/definitions.ts');
const resourceSourcePath = path.join(repoRoot, 'engine/src/automation/resourceCatalog.ts');

const startMarker = '<!-- BEGIN GENERATED GIZMO REFERENCE -->';
const endMarker = '<!-- END GENERATED GIZMO REFERENCE -->';

function extractArrayLiteral(source, constName) {
  const marker = `export const ${constName}`;
  const markerIndex = source.indexOf(marker);
  if (markerIndex === -1) {
    throw new Error(`Could not find ${constName}`);
  }

  const equalsIndex = source.indexOf('=', markerIndex);
  const firstBracket = source.indexOf('[', equalsIndex);
  if (equalsIndex === -1 || firstBracket === -1) {
    throw new Error(`Could not find array literal for ${constName}`);
  }

  let depth = 0;
  let quote = null;
  let escaped = false;

  for (let index = firstBracket; index < source.length; index += 1) {
    const char = source[index];

    if (quote) {
      if (escaped) {
        escaped = false;
      } else if (char === '\\') {
        escaped = true;
      } else if (char === quote) {
        quote = null;
      }
      continue;
    }

    if (char === '"' || char === "'" || char === '`') {
      quote = char;
      continue;
    }

    if (char === '[') depth += 1;
    if (char === ']') {
      depth -= 1;
      if (depth === 0) return source.slice(firstBracket, index + 1);
    }
  }

  throw new Error(`Could not parse array literal for ${constName}`);
}

function evaluateArrayLiteral(arrayLiteral, constName) {
  try {
    return Function(`"use strict"; return (${arrayLiteral});`)();
  } catch (error) {
    throw new Error(`Failed to evaluate ${constName}: ${error.message}`);
  }
}

async function readCatalogs() {
  const [commandSource, resourceSource] = await Promise.all([
    fs.readFile(commandSourcePath, 'utf8'),
    fs.readFile(resourceSourcePath, 'utf8'),
  ]);

  return {
    commands: evaluateArrayLiteral(
      extractArrayLiteral(commandSource, 'ENGINE_AUTOMATION_COMMAND_DEFINITIONS'),
      'ENGINE_AUTOMATION_COMMAND_DEFINITIONS',
    ),
    resources: evaluateArrayLiteral(
      extractArrayLiteral(resourceSource, 'ENGINE_AUTOMATION_RESOURCE_DEFINITIONS'),
      'ENGINE_AUTOMATION_RESOURCE_DEFINITIONS',
    ),
  };
}

function formatSignature(item) {
  const parameters = item.parameters ?? [];
  return `${item.name}(${parameters.map((parameter) => `${parameter.name}${parameter.required ? '' : '?'}`).join(', ')})`;
}

function formatCommand(command) {
  const flags = [
    command.changesState ? 'changes state' : 'session/read-only',
    command.persistsWorld ? 'persists world' : null,
  ].filter(Boolean).join('; ');
  return `- \`${formatSignature(command)}\`: ${command.description} (${flags})`;
}

function formatResource(resource) {
  const params = resource.kind === 'template'
    ? ` params: ${(resource.parameters ?? []).map((parameter) => parameter.name).join(', ')}`
    : ' params: none';
  return `- \`${resource.name}\`: ${resource.description}${params}`;
}

function renderGeneratedReference(commands, resources) {
  return [
    startMarker,
    '<!-- Generated by scripts/generate-skill.mjs. Do not edit this block by hand. -->',
    '',
    '## Embedded Engine Reference',
    '',
    'This block is generated from the installed engine automation catalogs so the',
    'skill remains useful when the source repo docs are not on disk. Use it for',
    'common shapes, then use `gizmo docs ...` for exact installed-version detail.',
    '',
    '### Automation Commands',
    '',
    ...commands.map(formatCommand),
    '',
    '### Automation Resources',
    '',
    ...resources.map(formatResource),
    '',
    '### High-Value Command Examples',
    '',
    'Add a cube:',
    '',
    '```bash',
    'gizmo call add-entity --params \'{"archetypeOrDef":"cube"}\'',
    '```',
    '',
    'Add an inline entity definition:',
    '',
    '```bash',
    'gizmo call add-entity --params \'{"archetypeOrDef":{"definition":{"Transform":{"position":{"x":0,"y":1,"z":0},"scale":{"x":2,"y":0.5,"z":2}},"Renderable":{"body":{"type":"box","size":{"x":2,"y":0.5,"z":2}}}},"archetype":"platform"}}\'',
    '```',
    '',
    'Move an entity by stable ID:',
    '',
    '```bash',
    'gizmo call set-transform --params \'{"stableId":12,"transform":{"position":{"x":2,"y":1,"z":0}}}\'',
    '```',
    '',
    'Modify a component after checking its schema:',
    '',
    '```bash',
    'gizmo docs component Transform',
    'gizmo call modify-component --params \'{"stableId":12,"componentName":"Transform","componentData":{"position":{"x":0,"y":2,"z":0}}}\'',
    '```',
    '',
    'Frame and capture visual output:',
    '',
    '```bash',
    'gizmo camera frame-entity 12',
    'gizmo snapshot --prefix entity-12',
    '```',
    '',
    'Batch one logical operation:',
    '',
    '```bash',
    'gizmo batch \'[{"name":"add-entity","params":{"archetypeOrDef":"cube"}},{"name":"add-entity","params":{"archetypeOrDef":"sphere","overrides":{"Transform":{"position":{"x":2,"y":1,"z":0}}}}}]\'',
    '```',
    '',
    '### Component And Body Authoring Notes',
    '',
    '- Components are keyed by component name in entity definitions.',
    '- Always inspect `gizmo resource component-catalog` or `gizmo docs component <name>` before using unfamiliar component fields.',
    '- Common transform fields are `position`, `rotation`, and `scale` with `{ "x", "y", "z" }` numeric objects.',
    '- Body definitions are nested objects used by renderable/composite entities. Use `modify-body`, `insert-body-part`, `add-body-part`, and `set-body-part-transform` for structural body edits.',
    '- Prefer small edits followed by `entity-bundle --stable-id <id>` so mistakes are easy to spot.',
    '',
    '### Visual Iteration Pattern',
    '',
    '1. Start with `gizmo start --no-open --port 0`, surface the live URL, and keep working.',
    '2. Make a meaningful first build immediately; do not wait for browser attachment.',
    '3. If no browser is attached, continue with file-backed edits such as `gizmo apply ./scene.json --world ./world.json`.',
    '4. Once a browser is attached, move the camera with `frame-entity` or `camera set`.',
    '5. Capture `gizmo snapshot` and compare against the user request.',
    '6. Repeat from another camera angle for spatial work.',
    '',
    endMarker,
  ].join('\n');
}

async function main() {
  const [{ commands, resources }, skill] = await Promise.all([
    readCatalogs(),
    fs.readFile(skillPath, 'utf8'),
  ]);

  const start = skill.indexOf(startMarker);
  const end = skill.indexOf(endMarker);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(`${path.relative(repoRoot, skillPath)} is missing generated reference markers`);
  }

  const next = [
    skill.slice(0, start).trimEnd(),
    renderGeneratedReference(commands, resources),
    skill.slice(end + endMarker.length).trimStart(),
  ].join('\n\n');

  if (next === skill) {
    console.log('Gizmo skill reference is up to date.');
    return;
  }

  if (checkOnly) {
    throw new Error('Gizmo skill reference is stale. Run `npm run skills:generate`.');
  }

  await fs.writeFile(skillPath, next, 'utf8');
  console.log(`Generated ${path.relative(repoRoot, skillPath)}`);
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
