// Generated by scripts/generate-worldscript-skill.mjs. Do not edit by hand.

export function buildWorldEditorPrompt(info: Record<string, any>, goal?: string): string {
  const base = [
    'Inspect engine://session/info and engine://world/summary before making edits.',
    'Use engine://entities and engine://entities/{stableId} for precise targeting.',
    info?.serverUrl ? `This MCP session is attached to live server ${info.serverUrl}.` : 'Mutating tools auto-save by default unless the server was started with no-auto-save.',
    info?.allowWorldScripts === true
      ? "WorldScript sessions can execute trusted local JavaScript. Use run-world-script for full world creation from scratch when allowWorldScripts is true. Prefer setupScene(api), api.initialize(definition, { merge: false, spawnEntities: true }), api.registerArchetype, and api.spawn. Author Body values as composite bodies with params.parts; each primitive part has geometry and material. Validate with run-world-script validate=true or read engine://world/scene-evaluation after changes."
      : 'WorldScript execution is not enabled in this MCP session; use non-script tools unless the user restarts with --allow-world-scripts.',
    goal ? `Goal: ${goal}` : '',
  ].filter(Boolean);
  return base.join(' ');
}
